// This file was autogenerated by print_selective_registration_header.py
#ifndef OPS_TO_REGISTER
#define OPS_TO_REGISTER
#define SHOULD_REGISTER_OP(op) true
#define SHOULD_REGISTER_OP_KERNEL(clz) true
#define SHOULD_REGISTER_OP_GRADIENT true
#endif
